services:
  db:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_DB: rust_server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Try2read
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - infra_net
    restart: unless-stopped

  backend:
    image: jagadesh31/backend:${TAG}
    expose:
      - "8080"
    environment:
      DATABASE_URL: "postgres://postgres:Try2read@db:5432/rust_server"
      RUST_LOG: "info"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - infra_net
    restart: on-failure:5

  frontend:
    image: jagadesh31/frontend:${TAG}
    expose:
      - "3000"
    networks:
      - infra_net
    restart: unless-stopped
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true

  nginx:
    image: jagadesh31/nginx:${TAG}
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - infra_net
    restart: unless-stopped

volumes:
  pgdata:

networks:
  infra_net:
    external: true